### PR TITLE
Remove references to host provisioning

### PR DESCRIPTION
**Pull request by gmcculloug**
Remove references to host provisioning.

Related to https://github.com/ManageIQ/manageiq/pull/17604

### CODE REVIEW

**Comment by gmcculloug** [comment]
@abellotti Not sure if there are any other changes required to remove host_provisioning from the repo.  Hoping you can take a quick look and advise.  Thanks.

**Comment by abellotti** [comment]
that's it for this repo.  The only question would be if there were current calls doing that and are we breaking/removing capability ?

**Comment by gmcculloug** [comment]
@abellotti This is old logic which is limited in functionality and I am not aware of anyone using it.  There are preferred tools, like https://www.theforeman.org for this task.

cc @Fryguy

**Comment by abellotti** [comment]
Thanks @gmcculloug for the spring cleaning.  LGTM!! 👍

**Pull request merged**
