### PR TITLE
Automate class CRUD

### PR DESCRIPTION
**Pull request by martinpovolny**
closes #https://github.com/ManageIQ/manageiq-api/issues/700

```
$ apic get automate_classes/721 --attributes=name,display_name,description,fqname
{
  "href": "http://localhost:3000/api/automate_classes/721",
  "name": "DynamicDialogs",
  "display_name": null,
  "description": null,
  "id": "721",
  "fqname": "/OP_Satellite/Integration/Satellite/DynamicDialogs"
}
```

### CODE REVIEW

**Comment by lpichler** [comment]
@mkanoor can you take a look 👀  please ?  Thanks!

**Comment by martinpovolny** [comment]
@mkanoor : any chance you check this soon? Or shall we ask someone else from automate?

**Comment by d-m-u** [comment]
@tinaafitz or @lfu please take a look

**Comment by martinpovolny** [comment]
@mkanoor, @d-m-u, @lfu, @tinaafitz  :eyes:  :eyes:  :eyes:

**Comment by lpichler** [comment]
Hi @mfeifer , do we have also GH project for API ? I think this PR is "ready for review" - not sure whether we have this state.

**Comment by mfeifer** [comment]
@lpichler we do, but it's pretty much automated at this point just to see where things are. We are not in full use of the projects feature....yet.

**Comment by chessbyte** [comment]
@abellotti @Fryguy can you guys take a look at this PR that was deemed good to go by both @d-m-u and @lpichler

**Comment by abellotti** [comment]
I think it's safe to go with this, since we restrict the edits on name, display_name and description. LGTM!!

**Pull request merged**
