### PR TITLE
Upgrade from FactoryGirl to FactoryBot

### PR DESCRIPTION
**Pull request by juliancheal**

### CODE REVIEW

**Comment by djberg96** [comment]
Hm, thought I did this already in https://github.com/ManageIQ/manageiq-api/pull/534. I guessed I missed one?

**Comment by kbrock** [comment]
```

**Comment by djberg96** [comment]
@kbrock I'm not seeing that locally, though. Maybe @juliancheal needs to rebase?

**Comment by juliancheal** [comment]
Rebased :)

**Comment by djberg96** [comment]
Yeah, now you're seeing the same two errors that I saw locally.

**Comment by kbrock** [comment]
@juliancheal Looks like master had the same problem. This was fixed 20 hours ago - please re-kick

This error feels very unrelated

**Pull request merged**
