### PR TITLE
Only show OPTIONS for supported providers

### PR DESCRIPTION
**Pull request by Fryguy**
@agrare Please review.

When I was working on the callers of leaf_subclasses, I noticed this.  If a provider type is blocked we should not be exposing it via the API.  Coincidentally, this actually helps me on the leaf_subclasses side, because it removes another caller...effectively I think leaf_subclasses should probably be a private method.

### CODE REVIEW

**Comment by Fryguy** [comment]
Marking as WIP because I also want to handle a direct query to an unsupported provider which I think is broken.

**Comment by Fryguy** [comment]
Updated now to also work for single provider queries.

**Review by agrare — APPROVED** [review]

**Comment by simaishi** [comment]
Kasparov backport details:

```
$ git log -1
commit 57c5948135362934440e8c1f52cb419ae0fd7579
Author: Adam Grare <agrare@redhat.com>
Date:   Wed Oct 28 14:35:20 2020 -0400

    Merge pull request #948 from Fryguy/only_supported_subclasses

    Only show OPTIONS for supported providers

    (cherry picked from commit 6096543dcfce5dd1ca1f6a8582cb7c834678a877)
```

**Comment by simaishi** [comment]
Jansa backport details:

```
$ git log -1
commit 6d2e5cc72573f401be948a6a796b1ddb4f40bcd5
Author: Adam Grare <agrare@redhat.com>
Date:   Wed Oct 28 14:35:20 2020 -0400

    Merge pull request #948 from Fryguy/only_supported_subclasses

    Only show OPTIONS for supported providers

    (cherry picked from commit 6096543dcfce5dd1ca1f6a8582cb7c834678a877)
```

**Pull request merged**
