### PR TITLE
Allow creation of AutomationManagers via API

### PR DESCRIPTION
**Pull request by agrare**
https://talk.manageiq.org/t/bad-request-when-trying-to-add-create-ansible-tower-providers-via-api/5394/3

### CODE REVIEW

**Comment by agrare** [comment]
I'm not sure if there is a reason why these managers aren't here, but I tested creating an ansible tower provider and it works fine.

The other missing manager types are:
1. ConfigurationManager
2. MonitoringManager
3. ProvisioningManager
4. StorageManager

I think the lack of ConfigurationManager and ProvisioningManager is due to the Provider type which translates to "provider_foreman_add_provider" (but we have other Provider subclasses, so who knows)

Not sure if anyone still cares about the MonitoringManager, and standalone storage managers are relatively new.

**Comment by Fryguy** [comment]
@agrare Should this go back?

**Comment by agrare** [comment]
@Fryguy yeah I think so

**Comment by Fryguy** [comment]
Backported to `lasker` in commit ee9d7feb568f92ff7da92d9d05d80be63e7a0250.

```text
commit ee9d7feb568f92ff7da92d9d05d80be63e7a0250
Author: Jason Frey <fryguy9@gmail.com>
Date:   Wed May 5 09:08:24 2021 -0400

    Merge pull request #1033 from agrare/allow_creation_of_automation_managers
    
    Allow creation of AutomationManagers via API
    
    (cherry picked from commit f125c702a22fc277b18a375001651d6eeb9bbe47)
```

**Pull request merged**
