### PR TITLE
[Changelog] Update for Hammer-5 release

### PR DESCRIPTION
**Pull request by JPrause**
[skip ci]

### CODE REVIEW

**Comment by JPrause** [comment]
@miq-bot add_label documentation

**Comment by JPrause** [comment]
@miq-bot add_label hammer/yes

**Comment by JPrause** [comment]
@abellotti as time permits, can you review/merge.

**Comment by simaishi** [comment]
Hammer backport details:

```
$ git log -1
commit 7a1821f29493bb7a7a0c7472236b97301fefe54c
Author: Alberto Bellotti <abellotti@users.noreply.github.com>
Date:   Thu Apr 18 18:28:34 2019 -0400

    Merge pull request #577 from JPrause/hammer5_cl
    
    [Changelog] Update for Hammer-5 release
    
    (cherry picked from commit 8746271c320c41e2c79471336df1fce053a8c4dc)
```

**Pull request merged**
