### PR TITLE
use OPTIONS /api/providers

### PR DESCRIPTION
**Pull request by enoodle**
This will allow creating dynamic UI based on the provider options description.

Reopening of https://github.com/ManageIQ/manageiq-api/pull/3 due to Travis problems.

### CODE REVIEW

**Comment by enoodle** [comment]
@jntullo @imtayadeway @abellotti PTAL

**Comment by simon3z** [comment]
@miq-bot assign abellotti 
@miq-bot add_label enhancement

**Comment by jntullo** [comment]
@enoodle LGTM, if you could just address the rubococp issue 😄

**Comment by enoodle** [comment]
@jntullo Fixed.

**Comment by abellotti** [comment]
Thanks @enoodle for the API enhancement !!  👍

**Pull request merged**
