### PR TITLE
[Changelog] Update for Hammer-6

### PR DESCRIPTION
**Pull request by JPrause**
[skip ci]

### CODE REVIEW

**Comment by JPrause** [comment]
@miq-bot add_label documentation

**Comment by JPrause** [comment]
@miq-bot add_label hammer/yes

**Comment by JPrause** [comment]
@abellotti as time permits, can you review/merge.

**Comment by simaishi** [comment]
Hammer backport details:

```
$ git log -1
commit bcbc558a1e651df7c15d77dbadb83c6e2bd31552
Author: Alberto Bellotti <abellotti@users.noreply.github.com>
Date:   Fri May 17 09:37:29 2019 -0400

    Merge pull request #592 from JPrause/hammer6_cl
    
    [Changelog] Update for Hammer-6
    
    (cherry picked from commit 58b8e9944deeb93224f928492d01d77a30fdd023)
```

**Pull request merged**
