### PR TITLE
[WIP] API endpoints for getting Schedules

### PR DESCRIPTION
**Pull request by vandrlov**
According to https://bugzilla.redhat.com/show_bug.cgi?id=1737708
adds API endpoint for GET /api/schedules and Specs for it. 

**Update**
- I added specs for different types of schedules.
- Progress on schedule_controller, but it still need some work.
- The spec need to be refractored, it looks ugly rn

Can you have a look at it @lpichler  ? :unicorn:

### CODE REVIEW

**Comment by vandrlov** [comment]
@miq-bot add_reviewer @lpichler

**Comment by lpichler** [comment]
WIP: we can finish it as whole thing

**Comment by chessbyte** [comment]
@vandrlov any update on this PR?

**Comment by chessbyte** [comment]
@vandrlov any update on this PR?

**Comment by chessbyte** [comment]
@vandrlov any update on this PR?

**Pull request closed without merging**
