### PR TITLE
Allow ordering ServiceTemplates with a schedule_time

### PR DESCRIPTION
**Pull request by bdunne**
Depends on: https://github.com/ManageIQ/manageiq/pull/17594

@AllenBW With this change, you can order now or schedule with `{ :action => "order", :schedule_time => "2018-06-15 21:26:43 UTC" }`

### CODE REVIEW

**Comment by AllenBW** [comment]
@bdunne yer a :godmode: 🙇‍♀️ 🏩 HAVE A GREAT VACAY

**Comment by AllenBW** [comment]
This will also need to be backported Gaprindashvili

**Comment by AllenBW** [comment]
@abellotti WOOOOOOOOH GOOD NEWS #17594 was merged! Could yah give this a quick 👁 ?

**Comment by abellotti** [comment]
Thanks @bdunne for the API Enhancement.  LGTM!!  👍

**Comment by bdunne** [comment]
@miq-bot add_label gaprindashvili/yes

**Comment by bdunne** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1564255

**Comment by simaishi** [comment]
Gaprindashvili backport details:

```
$ git log -1
commit 2c95b3d56e400586ba56b2758c4ee4d810d44d16
Author: Alberto Bellotti <abellotti@users.noreply.github.com>
Date:   Thu Jun 21 09:51:37 2018 -0400

    Merge pull request #400 from bdunne/order_service_template
    
    Allow ordering ServiceTemplates with a schedule_time
    (cherry picked from commit bc9cae59eaa0ec82677ffd93e99a30abb0a48ae5)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1608351
```

**Pull request merged**
