### PR TITLE
Allow set ownership screen for instances and images

### PR DESCRIPTION
**Pull request by lpichler**
fixes https://github.ibm.com/IBMPrivateCloud/CP4MCM/issues/15807

### CODE REVIEW

**Review by gtanzillo — APPROVED** [review]
@lpichler Looks good, it seems like the Travis failure is not related to your change but it does have to do with validating identifiers. But they look like they're different from the ones you're referencing in this PR. Can you confirm? Thanks

**Comment by lpichler** [comment]
@gtanzillo I am confirming that it. Identifies in CI failure are not relevant to this PR.

**Comment by lpichler** [comment]
based on https://github.ibm.com/IBMPrivateCloud/CP4MCM/issues/15807 it looks that it will be good to have it in Kasparov.

@miq-bot add_label kasparov/yes 

cc @simaishi

**Comment by abellotti** [comment]
Short and sweet 👍   with no new code needed !!  Thanks @lpichler for the API Enhancement.

**Comment by simaishi** [comment]
Kasparov backport details:

```
$ git log -1
commit cbb97d42648a5f08db75e955aea4487c89e5f587
Author: Gregg Tanzillo <gtanzill@redhat.com>
Date:   Mon Nov 30 09:50:24 2020 -0500

    Merge pull request #969 from lpichler/allow_set_ownership_screen_for_instances_and_images

    Allow set ownership screen for instances and images

    (cherry picked from commit 0a2e7be5915f47ca0d3e9a5c837191e0742157d0)
```

**Pull request merged**
