### PR TITLE
Adding ability to override encrypted attribute behavior in responses

### PR DESCRIPTION
**Pull request by abellotti**
Adding support for resource action options that are controller driven and not api.yml driven.

We needed the ability to override the default behavior of hiding encrypted attributes in responses for the refresh_dialog_field action when exercised on a resource.  This was causing the UI to hang when fields being refreshed via automate were encrypted (i.e. passwords) and never returned to the caller.

This needed to be implemented without breaking any of the behavior for all other actions and queries.

Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1705021

/cc @tinaafitz

### CODE REVIEW

**Comment by abellotti** [comment]
Marking as WIP as I need to test some more and add specs.

**Comment by abellotti** [comment]
_Note_: now that we can enable/disable encrypted attrs in responses, we may want to encrypt those for refresh_dialog_field if not already (v2/other) but would need corresponding UI changes too.

**Comment by simaishi** [comment]
@abellotti `ivanchuk/yes` and `hammer/yes`?

**Comment by abellotti** [comment]
Invanchuk is ok.  @tinaafitz is this needed for hammer too ?

**Comment by simaishi** [comment]
Ivanchuk backport details:

```
$ git log -1
commit 531cecf68c7d8d9a2715e31a7dc46061145b4a88
Author: Gregg Tanzillo <gtanzill@redhat.com>
Date:   Fri Aug 9 17:22:10 2019 -0400

    Merge pull request #646 from abellotti/allow_encrypted_fields_for_refresh_dialog_action
    
    Adding ability to override encrypted attribute behavior in responses
    
    (cherry picked from commit 2fa9a6f9ccc300b6dda490412183694f2f025851)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1705021
```

**Comment by simaishi** [comment]
@abellotti The BZ is targeted for hammer. Please add `hammer/yes` if this can be backported to hammer branch as is. Thanks!

**Comment by abellotti** [comment]
Doesn't look like it can be backported to hammer,  FactoryGirl -> FactoryBot for one in the specs.

**Comment by simaishi** [comment]
FactoryGirl/Bot is ok, either one works in hammer. It's ok otherwise? I can resolve minor conflicts. No other dependency?

**Comment by abellotti** [comment]
Ok, just tested good with Hammer. For backport, yea, just FactoryBot -> FactoryGirl, and the api_resource_actions method merged anywhere under the private declaration in app/controllers/api/service_dialogs_controller.rb will work.

**Comment by simaishi** [comment]
Thanks @abellotti

**Comment by simaishi** [comment]
Hammer backport details:

```
$ git log -1
commit 1571d1be96d24e7d07d749e371a8eff48b0f2746
Author: Gregg Tanzillo <gtanzill@redhat.com>
Date:   Fri Aug 9 17:22:10 2019 -0400

    Merge pull request #646 from abellotti/allow_encrypted_fields_for_refresh_dialog_action
    
    Adding ability to override encrypted attribute behavior in responses
    
    (cherry picked from commit 2fa9a6f9ccc300b6dda490412183694f2f025851)
    
    Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1740844
```

**Pull request merged**
