### PR TITLE
[Changelog] Update for Hammer-9

### PR DESCRIPTION
**Pull request by JPrause**
[skip ci]

### CODE REVIEW

**Comment by JPrause** [comment]
@miq-bot add_label documentation

**Comment by JPrause** [comment]
@miq-bot add_label hammer/yes

**Comment by JPrause** [comment]
@abellotti as time permits, can you review/merge.

**Comment by simaishi** [comment]
Hammer backport details:

```
$ git log -1
commit 5a918ffb0d0dd766fe24b27fa38728b8c994a8e8
Author: Alberto Bellotti <abellotti@users.noreply.github.com>
Date:   Fri Jul 19 11:01:12 2019 -0400

    Merge pull request #627 from JPrause/hammer9_cl
    
    [Changelog] Update for Hammer-9
    
    (cherry picked from commit d62e4b59448b856db1055f56c5b35835ff49da31)
```

**Pull request merged**
