### PR TITLE
Ensure that correct target is passed to resource_search on dialog refresh

### PR DESCRIPTION
**Pull request by jntullo**
Currently, the API assumes that a pluralized target_type will match that of a collection class type. This is not the case, as can be seen from `service_template_ansible_tower`. This ensures that a valid resource class and type is returned from the given target_type. In addition, this will raise a bad request error for invalid target_types rather than raising an internal server error

Resolves https://bugzilla.redhat.com/show_bug.cgi?id=1524227

cc: @himdel 
@miq-bot add_label bug, blocker, gaprindashvili/yes

### CODE REVIEW

**Comment by himdel** [comment]
LGTM, instead of a 500, I now get reasonable-looking data back :).

**Comment by jntullo** [comment]
@miq-bot assign @abellotti

**Comment by abellotti** [comment]
This looks good, maybe just add a test in spec/lib/api/collection_config_spec.rb that tests name_for_subclass usage by String.

**Comment by abellotti** [comment]
LGTM!! @jntullo Thanks for fixing this 😍 

will merge when 🍏

**Comment by simaishi** [comment]
Gaprindashvili backport details:

```
$ git log -1
commit eca6bafebe786c33b22b8d11c649c51a4add6330
Author: Alberto Bellotti <abellotti@users.noreply.github.com>
Date:   Wed Dec 13 12:02:15 2017 -0500

    Merge pull request #246 from jntullo/bz_1524227
    
    Ensure that correct target is passed to resource_search on dialog refresh
    (cherry picked from commit 8b7e6a2fa82641f53eeae6d1302a3437d5b7b4f9)
    
    Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1526057
```

**Pull request merged**
