### PR TITLE
Enable add and edit resource for /api/policy_profiles endpoint

### PR DESCRIPTION
**Pull request by gtanzillo**
Fixes: #748

### CODE REVIEW

**Comment by Fryguy** [comment]
@gtanzillo Do we know why they were disabled?

**Comment by gtanzillo** [comment]
@Fryguy 
>@gtanzillo Do we know why they were disabled?

I don't know, Tim Wade added the Policy APIs four years ago and he never enabled the profiles, for some reason.

**Comment by abellotti** [comment]
Just the rubocop warnings, and waiting for the specs.  👍

**Comment by abellotti** [comment]
Yeay, 🍏   Thanks @gtanzillo for the API Enhancement!!

**Comment by simaishi** [comment]
Ivanchuk backport details:

```
$ git log -1
commit c330a9c6b8bf41ab1ef1278a1154d717d244e317
Author: Alberto Bellotti <abellotti@users.noreply.github.com>
Date:   Mon Feb 24 13:03:15 2020 -0500

    Merge pull request #749 from gtanzillo/enable-add-edit-policy-profiles

    Enable add and edit resource for /api/policy_profiles endpoint

    (cherry picked from commit 32ea08e8a31da847d5a3cf607733ed75b58bea6f)

    Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1806702
```

**Pull request merged**
