### PR TITLE
Fix API action identifier verification check spec.

### PR DESCRIPTION
**Pull request by abellotti**
Fix API action identifier verification check spec.

- We were not looking at all identifiers, essentially cross-checking only 79 out of 490 current identifiers.

### CODE REVIEW

**Comment by abellotti** [comment]
Dangling Identifiers so checked for in API, but do not exist in Product Features.
  - configuration_script_view
  - conversion_host_delete
  - conversion_host_edit
  - conversion_host_new
  - host_new
  - load_balancer_show
  - load_balancer_show_list
  - miq_widget_show
  - miq_widget_show_list
  - pxe_server_create

Unless those endpoints have alternate identifiers, those API's aren't authorized and thus are not currently being called.

**Comment by abellotti** [comment]
ping @h-kataria can you take a 👀 when you get a chance ? Thanks.

**Comment by abellotti** [comment]
@gtanzillo  jansa/yes ?  If so we'd also need https://github.com/ManageIQ/manageiq-api/pull/841 backported.

**Comment by abellotti** [comment]
Marked https://github.com/ManageIQ/manageiq-api/pull/841 as jansa/yes since this PR depends on it too.

**Comment by simaishi** [comment]
Jansa backport details:

```
$ git log -1
commit e6f04828d13fc13abd676fabde35c252111ab459
Author: Gregg Tanzillo <gtanzill@redhat.com>
Date:   Fri May 29 16:05:22 2020 -0400

    Merge pull request #840 from abellotti/fix_action_identifier_verification

    Fix API action identifier verification check spec.

    (cherry picked from commit 263dadb43e65dc1eaa9b8e5d4b6e3158ef6ebba0)
```

**Pull request merged**
