### PR TITLE
Allow retirement requests to be created through the api

### PR DESCRIPTION
**Pull request by bdunne**
https://bugzilla.redhat.com/show_bug.cgi?id=1604016

### CODE REVIEW

**Comment by bdunne** [comment]
@miq-bot add_labels gaprindashvili/yes
@miq-bot add_labels enhancement
@miq-bot add_labels bug

**Comment by bdunne** [comment]
@miq-bot rm_label gaprindashvili/yes

**Comment by d-m-u** [comment]
Do we test these?

**Comment by bdunne** [comment]
@abellotti do you think we need tests for this?

**Comment by abellotti** [comment]
same boat as all the other subtype of request, so not immediately.  Maybe add a basic test to make sure those classes are honored (to catch compatibility/breaking changes from model).

**Comment by bdunne** [comment]
@abellotti tests updated as requested

**Comment by abellotti** [comment]
Thanks @bdunne for the update and API enhancement. LGTM!! 👍

**Pull request merged**
