### PR TITLE
Adding support for /api/containers primary collection.

### PR DESCRIPTION
**Pull request by abellotti**
Adding support for /api/containers primary collection

  GET /api/containers
  GET /api/containers/:id
  POST /api/containers      - bulk action "query"

Requires: https://github.com/ManageIQ/manageiq/pull/17074

https://bugzilla.redhat.com/show_bug.cgi?id=1549661

### CODE REVIEW

**Comment by abellotti** [comment]
ping @h-kataria couldn't find the individual resources product feature:

screen shot 2018-02-28 at 9 32 02 am

so just using the List.

Is this something we need to add to the product features, i.e. adding a Show identifier for Containers ? Thanks.

**Comment by h-kataria** [comment]
@abellotti looks like a "Show" feature is missing for Individual Container object, should have been a feature similar to https://github.com/ManageIQ/manageiq/blob/master/db/fixtures/miq_product_features.yml#L3639-L3642

containers_features

**Comment by jntullo** [comment]
LGTM! 👍

**Comment by simaishi** [comment]
Gaprindashvili backport details:

```
$ git log -1
commit a0aac4ab752288a2de3bb674c05108329f3652ff
Author: Jillian Tullo <jntullo@bu.edu>
Date:   Fri Mar 2 07:10:38 2018 -0800

    Merge pull request #332 from abellotti/support_containers
    
    Adding support for /api/containers primary collection.
    (cherry picked from commit 43def7167c9484cb7dc2774ac56943a8a92070ed)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1552809
```

**Pull request merged**
