### PR TITLE
Append RBAC features for VMRC console request through the API

### PR DESCRIPTION
**Pull request by skateman**
Adding these features for exposing API support for requesting VMRC consoles.

Parent issue: https://github.com/ManageIQ/manageiq/issues/18718
Depends on: https://github.com/ManageIQ/manageiq/pull/19097
@miq-bot add_label hammer/no, changelog/yes, enhancement
@miq-bot add_reviewer @lpichler

### CODE REVIEW

**Comment by skateman** [comment]
@miq-bot add_reviewer @abellotti

**Comment by skateman** [comment]
Waiting for PM to determine if this is ivanchuk/yes, but is ready to merge now. 

@miq-bot rm_label pending core

**Comment by skateman** [comment]
@miq-bot add_label ivanchuk/yes

**Comment by simaishi** [comment]
Ivanchuk backport details:

```
$ git log -1
commit 271130ad3ddfa8a966075f5cae6475d41ad88948
Author: Libor Pichler <lpichler@redhat.com>
Date:   Wed Aug 7 16:21:24 2019 +0200

    Merge pull request #642 from skateman/api-vmrc-support
    
    Append RBAC features for VMRC console request through the API
    
    (cherry picked from commit f9bb01225be6e503a0d8aa906e0eb193d587d4ce)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1740691
```

**Pull request merged**
