### PR TITLE
Use the replacement backend method for searching and valiating VMs

### PR DESCRIPTION
**Pull request by AparnaKarve**
This PR basically replaces `validate_vms` with `search_vms_and_validate`

To be merged after https://github.com/ManageIQ/manageiq/pull/17364 is merged

### CODE REVIEW

**Comment by gmcculloug** [comment]
@abellotti @gtanzillo Can you recommend an assignee for this?

@miq-bot add_label enhancement, transformation

**Comment by lfu** [comment]
@AparnaKarve Can you address the Travis failure? Thanks.

**Comment by AparnaKarve** [comment]
@lfu The Travis failure is related to the fact that  ManageIQ/manageiq#17364 is still not merged.
Once it gets merged, we should re-run Travis here, and bring it to green.

**Comment by gmcculloug** [comment]
@AparnaKarve @lfu Please see failing tests after core PR merged.

**Comment by AparnaKarve** [comment]
@gmcculloug @lfu Fixed the tests

@abellotti This should be good to go

**Comment by abellotti** [comment]
are we ok with the changed signature coming back from the method/thus REST API ?  Aren't current callers be broken ?

**Comment by gmcculloug** [comment]
Only caller today would be https://github.com/ManageIQ/manageiq-v2v/pull/618.

@AparnaKarve Can you confirm that you are expecting these keys to change?

**Comment by AparnaKarve** [comment]
@abellotti As Greg mentioned above, v2v is the only caller.

In ManageIQ/manageiq-v2v#618 I have taken into account the changed signature coming back from the API/method.

**Comment by AparnaKarve** [comment]
@abellotti Can we merge this today?
Without this PR and ManageIQ/manageiq-v2v#618, v2v would be broken in the nightly build tonight.

**Pull request merged**
