### PR TITLE
[Changelog] Update for Sprint 118

### PR DESCRIPTION
**Pull request by JPrause**
[skip ci]

### CODE REVIEW

**Comment by JPrause** [comment]
@miq-bot add_label documentation

**Comment by JPrause** [comment]
@simaishi here's the PR in the correct repo.

**Comment by simaishi** [comment]
@abellotti only 1 PR is mareked as `changelog/yes` for Sprint 118. Is this the only one we want to add?

**Comment by abellotti** [comment]
good catch @simaishi we also need https://github.com/ManageIQ/manageiq-api/pull/636, I just set the flag there.  Thanks!

**Comment by abellotti** [comment]
Thanks @JPrause for updating this. 👍

**Pull request merged**
