### PR TITLE
[IVANCHUK] Fix storing ae_attributes as uri_attributes for create/edit in CustomButtons

### PR DESCRIPTION
**Pull request by mzazrivec**
This is ivanchuk version of https://github.com/ManageIQ/manageiq-api/pull/967

@miq-bot add_label bug

The backport PR is needed in ivanchuk for https://bugzilla.redhat.com/show_bug.cgi?id=1892811

### CODE REVIEW

**Comment by mzazrivec** [comment]
@miq-bot add_reviewer @gtanzillo

**Comment by mzazrivec** [comment]
> Travis failures seem related?

Yep, related. I had to cherry-pick commits from https://github.com/ManageIQ/manageiq-api/pull/812 to make this work in ivanchuk.

**Comment by simaishi** [comment]
@gtanzillo or @lpichler  please review.

**Review by lpichler — APPROVED** [review]
👍  Thanks

**Pull request merged**
