### PR TITLE
add ability to set custom attributes on services via api

### PR DESCRIPTION
**Pull request by ailisp**
Issue: missing ability to set custom attributes on services via api, which is now fixed

BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1481547

\cc @abellotti @gtanzillo 
@miq-bot add-label wip, bug

### CODE REVIEW

**Comment by abellotti** [comment]
api.yml declaration (identifiers for the subcollection actions, see vms/instances/providers for example), also, the specs would be needed, also look at instances for reference.  Thanks!!

**Comment by ailisp** [comment]
@abellotti Hi, should we do similar spec instances_spec.rb and services_spec.rb for custom attributes. Or, since they're almost the same, test for custom_attributes mixin.

**Comment by ailisp** [comment]
@miq-bot remove-label wip

**Comment by abellotti** [comment]
Thanks @ailisp for the API Enhancement !! 👍 

The Hakiri warning above is unrelated and was taken care in a separate PR so I'll go ahead and merge.

**Pull request merged**
