### PR TITLE
Creating PhysicalChassis controller and adding endpoint configuration

### PR DESCRIPTION
**Pull request by EsdrasVP**
**This PR adds:**
- GET /api/physical_chassis
- GET /api/physical_chassis/:id
- POST /api/physical_chassis (action: refresh)
- POST /api/physical_chassis/:id (action: refresh)

**Depends on:**
[ManageIQ/manageiq#17320](https://github.com/ManageIQ/manageiq/pull/17320) [Merged]
[ManageIQ/manageiq-api#364](https://github.com/ManageIQ/manageiq-api/pull/364) [Merged]

### CODE REVIEW

**Comment by abellotti** [comment]
without this PR you can still access them as a relationship, i.e. GET /api/providers/:id?attributes=physical_chassis.  Is the /api/physical_chassis  or formal subcollection i.e. GET /api/providers/:id/physical_chassis needed ? If so you'd need an miq product feature identifier for it (manageiq/db/fixtures/miq_product_features.yml) so we can specify the :identifier: entries in the api.yml accordingly (RBAC purposes). Thanks.

**Comment by EsdrasVP** [comment]
@abellotti Thank you for the reminder. I put all the necessary identifiers in api.yml and miq_product_features.yml for both GET and POST features.

**Comment by abellotti** [comment]
ping @EsdrasVP can you revisit ? looks like the dependent PRs were merged.

**Comment by EsdrasVP** [comment]
@abellotti I revised and now both code climate and travis are passing.

**Comment by abellotti** [comment]
Thanks @EsdrasVP for the API Enhancement. LGTM !!  👍

**Pull request merged**
