### PR TITLE
[DEPENDS ON ManageIQ/manageiq#17672] Add ServiceTemplate#schedules subcollection

### PR DESCRIPTION
**Pull request by bdunne**
Depends on: https://github.com/ManageIQ/manageiq/pull/17672
Enables viewing schedules for ServiceTemplates for V2V
https://bugzilla.redhat.com/show_bug.cgi?id=1564255

### CODE REVIEW

**Comment by bdunne** [comment]
@miq-bot add_label gaprindashvili/yes

**Comment by JPrause** [comment]
@miq-bot add_label blocker

**Comment by simaishi** [comment]
Gaprindashvili backport details:

```
$ git log -1
commit 78795ebbd213a185b13d630b10d3559cd56e92c2
Author: Gregg Tanzillo <gtanzill@redhat.com>
Date:   Mon Jul 9 14:40:35 2018 -0400

    Merge pull request #412 from bdunne/service_template_view_schedules
    
    [DEPENDS ON ManageIQ/manageiq#17672] Add ServiceTemplate#schedules subcollection
    (cherry picked from commit 74851f182102df596e808944eafb19f518acd6a2)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1608351
```

**Comment by simaishi** [comment]
@bdunne Can you please take a look at Travis failures for Gaprindashvili branch?
https://travis-ci.org/ManageIQ/manageiq-api/builds/408072881

```
NoMethodError:
       undefined method `resource_id=' for #<MiqSchedule:0x0000001911c330>
```

**Comment by bdunne** [comment]
https://github.com/ManageIQ/manageiq/pull/17594 and https://github.com/ManageIQ/manageiq/pull/17588 and https://github.com/ManageIQ/manageiq/pull/17581 also need backport.

**Comment by simaishi** [comment]
@bdunne Thank you. I backported https://github.com/ManageIQ/manageiq/pull/17588 and https://github.com/ManageIQ/manageiq/pull/17581. Will wait for you to create a Gaprindashvili PR for https://github.com/ManageIQ/manageiq/pull/17594 and re-run Travis.

**Pull request merged**
