### PR TITLE
Add simulate action for policy simulation.

### PR DESCRIPTION
**Pull request by lfu**
https://github.com/ManageIQ/manageiq-api/issues/936

@miq-bot add_label enhancement, kasparov/no

```
POST /api/vms
{
    "action": "simulate_policy",
    "event": "request_vm_poweroff",
    "targets": [
        {"id" : "10000000000001"},
        {"href": "http://localhost:3000/api/vms/10000000000003"},
        {"guid": "dcb564ce-801f-429a-8865-01d252d5ece7"}
    ]
}

{
    "success": true,
    "message": "Simulating policy on event request_vm_poweroff for targets [vms] ID: [10000000000001, 10000000000003, 10000000000870]",
    "task_id": "10000000053328",
    "task_href": "http://localhost:3000/api/tasks/10000000053328"
}
```

```
POST /api/vms
{
    "action": "simulate_policy",
    "resources": [
        {"id" : "10000000000001", "event": "request_vm_poweroff"},
        {"id" : "10000000000002", "event": "request_vm_poweroff"}
    ]
}

{
    "results": [
        {
            "success": true,
            "message": "Vm id:10000000000001 name: 'jrnettest' simulating policy on event request_vm_poweroff",
            "task_id": "10000000053329",
            "task_href": "http://localhost:3000/api/tasks/10000000053329",
            "href": "http://localhost:3000/api/vms/10000000000001"
        },
        {
            "success": true,
            "message": "Vm id:10000000000002 name: 'RHEL72_1' simulating policy on event request_vm_poweroff",
            "task_id": "10000000053330",
            "task_href": "http://localhost:3000/api/tasks/10000000053330",
            "href": "http://localhost:3000/api/vms/10000000000002"
        }
    ]
}
```

```
POST /api/vms/10000000000001
{
    "action": "simulate_policy",
    "event": "vm_poweroff"
}

{
    "success": true,
    "message": "Vm id:10000000000001 name: 'jrnettest' simulating policy on event vm_poweroff",
    "task_id": "10000000053331",
    "task_href": "http://localhost:3000/api/tasks/10000000053331",
    "href": "http://localhost:3000/api/vms/10000000000001"
}
```

### CODE REVIEW

**Comment by lfu** [comment]
Is this looking good as a request body for bulk action?
```
{
    "action": "simulate",
    "policy": {
      "event": "reqquest_vm_poweroff",
      "resources": [
        {"id" : "10000000000001"},
        {"id" : "10000000000002"}
      ]
    }  
}
```

**Comment by abellotti** [comment]
bulk action in the API is intended for triggering an action while targeting multiple resources in a single request, i.e. in https://www.manageiq.org/docs/reference/latest/api/reference/vms.html look at starting multiple vms.

bulk action on vms in this PR would mean triggering the simulate action on multiple VMS, i.e.:

```
POST /api/vms

{
  "action" : "simulate",
  "resources" : [
      { "href" : "http://localhost:3000/api/vms/111", "policy" : { "event" : "request_vm_poweroff" } },
      { "href" : "http://localhost:3000/api/vms/112", "policy" : { "event" : "request_vm_poweroff" } },
      ...
   ]
}
```

Just using href in this example to show we're picking Vms, id, guid, etc. can also be used.

**Comment by gtanzillo** [comment]
After discussion, we agreed on this format for the request -
```
{
    "action": "simulate",
    "event": "request_vm_poweroff",
    "resources": [
      {"id" : "10000000000001"},
      {"id" : "10000000000002"}
    ]
}
```

**Comment by chessbyte** [comment]
@gtanzillo since there are only ids, without hrefs, will the event itself force the determination of which type of resource each is?

**Comment by Fryguy** [comment]
@chessbyte The action applies to a collection (e.g. `/api/vms`) or a resource (e.g. `/api/vms/1`), so the object type is implied.  Note that while the example there uses `id`s, one can also pass hrefs, and I'd expect we use the common helper method that parses resource objects.

We also discussed naming the method `simulate_vm_policy` for clarity.  In fact, now that I read that, `simulate` isn't a good enough action name by itself, and at a minimum should have the word `policy` in there somewhere to qualify it.

**Comment by Fryguy** [comment]
To add a little more clarity based on a question that was over in the issue.  If you were targeting non-VMs (e.g. the clusters dropdown), the payload would be similar:

`POST /api/cluster`

```json
{
    "action": "simulate_vm_policy",
    "event": "request_vm_poweroff",
    "resources": [
      {"id" : "10000000000001"},
      {"id" : "10000000000002"}
    ]
}
```

where those are cluster ids.  You're effectively asking "run the policies on all of the vms in these clusters, kicking it with the `request_vm_poweroff` event"

**Comment by lfu** [comment]
If we want to use a method like `simulate_collection` to handle the bulk action, `resources` key can't exist at the root level of the request body hash due to [this line](https://github.com/ManageIQ/manageiq-api/blob/e174d80c96ca3f9f796ad5aa70c680752a99f9c3/app/controllers/api/base_controller/manager.rb#L9). Once there is `resources` key at the root level of the hash, `_collection` method would be skipped and `_resource` method would be called.

Could I suggest the following format:
```
POST /api/vms

{
    "action": "simulate_policy",
    "event": "request_vm_poweroff",
    "targets": [
      {"id" : "10000000000001"},
      {"id" : "10000000000002"}
    ]
}
```
Or something like:
```
{
    "action": "simulate_policy",
    "event": "request_vm_poweroff",
    "target_ids": [
      "10000000000001",
      "10000000000002"
    ]
}
```

**Review by abellotti — APPROVED** [review]

**Review by gtanzillo — APPROVED** [review]

**Pull request merged**
