### PR TITLE
Remove Middleware API

### PR DESCRIPTION
**Pull request by cfcosta**
Middleware Manager is being phased out, so is the API.

@miq-bot add_label gaprindashvili/yes

### CODE REVIEW

**Comment by abonas** [comment]
@miq-bot add_label providers/middleware

**Comment by abonas** [comment]
@cfcosta if this is an "as is" revert of the previous commit, it's better (and more clear) to send a regular revert

**Comment by cfcosta** [comment]
@abonas not exactly, it is a revert of the whole PR merge. It's the cleanest way of doing it, but it squashes all commits from the PR into one.

**Comment by abonas** [comment]
OK thanks

**Comment by abonas** [comment]
@abellotti @imtayadeway

**Comment by abonas** [comment]
test failures seem unrelated from a quick glance

**Comment by imtayadeway** [comment]
@cfcosta agreeing with @abonas - was this done by hand? If you do:

```
git revert -m 1 <sha of the merge commit>
```

It will add useful documentation for future git historians by linking to the original merge commit, and also providing details of any conflicts that needed to be fixed by hand.

**Comment by abellotti** [comment]
ping @cfcosta when you get a chance to push the git revert commit instead, Thanks!!

**Comment by cfcosta** [comment]
@imtayadeway @abellotti it was not done by hand, I did the `git revert -m 1` but reworded the commit to provide more context. Either way, done!

**Comment by simaishi** [comment]
Gaprindashvili backport details:

```
$ git log -1
commit 5d89abd08f0b1a90dd109b3a1d6601ede7db8f45
Author: Tim Wade <imtayadeway@users.noreply.github.com>
Date:   Tue Jan 2 13:03:57 2018 -0800

    Merge pull request #255 from cfcosta/remove-middleware-api
    
    Remove Middleware API
    (cherry picked from commit f4f2ca76db3584f5e5a665c708c2d8bff169479c)
```

**Pull request merged**
