### PR TITLE
Allow read-only access to quotas subcollection

### PR DESCRIPTION
**Pull request by jntullo**
This change allows read-only access to the quotas subcollection on tenants 

@miq-bot add_label gaprindashvili/yes 
@miq-bot assign @abellotti

### CODE REVIEW

**Comment by abellotti** [comment]
@jntullo LGTM!!  can we get this PR's tires kicked by who reported the issue ?  would like to make sure before we merge as it is also g/yes. Thanks.

**Comment by jntullo** [comment]
cc @ITD27M01 - can you review and see if this resolves your issue for read-only on quotas? Thanks!

**Comment by ITD27M01** [comment]
@jntullo Thank you! Is there any way to get this backported to fine and to CFME 5.8 ?

**Comment by jntullo** [comment]
BZ for Fine backport: https://bugzilla.redhat.com/show_bug.cgi?id=1535556 

@miq-bot add_label fine/yes

**Comment by abellotti** [comment]
Ping @ITD27M01 any update on your testing ?  Did the fix work for you ?

**Comment by ITD27M01** [comment]
@abellotti I have checked this on CFME 5.8.2 appliance (MIQ FIne) and seems it works fine, but I want to get users response for this. I provided access to some users to a test environment and wait for their response.

**Comment by abellotti** [comment]
LGTM!! Thanks @jntullo for fixing this and @ITD27M01 for checking it out.  👍

**Comment by simaishi** [comment]
Fine backport details:

```
$ git log -1
commit c9069c107c1da93f08827be4f3428da0dbf437c3
Author: Alberto Bellotti <abellotti@users.noreply.github.com>
Date:   Tue Jan 23 11:07:38 2018 -0500

    Merge pull request #283 from jntullo/quota_product_features
    
    Allow read-only access to quotas subcollection
    (cherry picked from commit 9f9f4ee94265c35dff43392725517dca19ac7d48)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1550737
```

**Comment by simaishi** [comment]
Gaprindashvili backport details:

```
$ git log -1
commit a3551dab791d39e1856fcf6a7fa7ec7cb6945ef4
Author: Alberto Bellotti <abellotti@users.noreply.github.com>
Date:   Tue Jan 23 11:07:38 2018 -0500

    Merge pull request #283 from jntullo/quota_product_features
    
    Allow read-only access to quotas subcollection
    (cherry picked from commit 9f9f4ee94265c35dff43392725517dca19ac7d48)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1550736
```

**Pull request merged**
