### PR TITLE
[Changelog] Update for Hammer-1

### PR DESCRIPTION
**Pull request by JPrause**
[skip ci]

### CODE REVIEW

**Comment by JPrause** [comment]
@miq-bot add_label documentation

**Comment by JPrause** [comment]
@miq-bot assign simaishi

**Comment by simaishi** [comment]
@JPrause PR 473 under "Sprint 96 ending 2018-10-08" should move up to Hammer-1.

**Comment by simaishi** [comment]
Hammer backport details:

```
$ git log -1
commit 943dd60266c79a2440f80c827c882144a058cfb7
Author: Satoe Imaishi <simaishi@redhat.com>
Date:   Wed Jan 9 15:32:49 2019 -0500

    Merge pull request #538 from JPrause/hammer1_cl
    
    [Changelog] Update for Hammer-1
    
    (cherry picked from commit bf02aabec84361f3112ef83a8cc6bf876d547198)
```

**Pull request merged**
