### PR TITLE
fix the custom button create

### PR DESCRIPTION
**Pull request by d-m-u**
currently is broken with the error handling and updating a nil

surely this is small enough to get approval?

@miq-bot add_label bug 
fixes https://bugzilla.redhat.com/show_bug.cgi?id=1827818

### CODE REVIEW

**Comment by d-m-u** [comment]
@miq-bot add_label jansa/yes, ivanchuk/yes

**Comment by d-m-u** [comment]
anyone want to look at this?

**Comment by d-m-u** [comment]
could i please get this reviewed?

**Comment by yrudman** [comment]
@miq-bot add-label blocker

duplicate BZ https://bugzilla.redhat.com/show_bug.cgi?id=1829279 is ```blocker```

**Comment by simaishi** [comment]
Jansa backport details:

```
$ git log -1
commit 7ee5c5aefbe7d742d3813ce8a165b91bb317d8ae
Author: Brandon Dunne <bdunne@redhat.com>
Date:   Wed Apr 29 15:33:53 2020 -0400

    Merge pull request #814 from d-m-u/custom_buttons_take_two

    fix the custom button create

    (cherry picked from commit 6b3146014c9740b3048a5e12d0c180a042f0840c)

    https://bugzilla.redhat.com/show_bug.cgi?id=1827818
```

**Comment by simaishi** [comment]
Ivanchuk backport details:

```
$ git log -1
commit 48fdfa0a788cdcd3ba3e8ce7177e46f21d4674dd
Author: Brandon Dunne <bdunne@redhat.com>
Date:   Wed Apr 29 15:33:53 2020 -0400

    Merge pull request #814 from d-m-u/custom_buttons_take_two

    fix the custom button create

    (cherry picked from commit 6b3146014c9740b3048a5e12d0c180a042f0840c)

    https://bugzilla.redhat.com/show_bug.cgi?id=1827818
```

**Pull request merged**
