### PR TITLE
Remove container provider resume/pause

### PR DESCRIPTION
**Pull request by d-m-u**
Ability to pause/resume a container provider has been removed from the UI but it still accessible 
via the API.

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1750480

### CODE REVIEW

**Comment by d-m-u** [comment]
Green on ops-ui and core. 
@miq-bot add_label technical debt, bug

**Comment by agrare** [comment]
@d-m-u do you have a cross-repo test pr?

**Comment by d-m-u** [comment]
@agrare I ran UI and core specs locally, do you need the cross-repo too?

**Comment by agrare** [comment]
@d-m-u yes just to be safe, thanks

**Comment by d-m-u** [comment]
thanks @agrare

**Comment by simaishi** [comment]
@d-m-u can this be `ivanchuk/yes`?

**Comment by d-m-u** [comment]
@miq-bot add_label ivanchuk/yes

**Comment by simaishi** [comment]
Ivanchuk backport details:

```
$ git log -1
commit e025d675087172a27615522a9fad54ab4f621714
Author: Adam Grare <agrare@redhat.com>
Date:   Fri Feb 14 14:00:11 2020 -0500

    Merge pull request #740 from d-m-u/removing_provider_resume_pause

    Remove container provider resume/pause

    (cherry picked from commit 086814a4a80cd1e83e2125338f96859d94394b20)

    Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1805902
```

**Pull request merged**
