### PR TITLE
Allow reconfigure vm on OSP provider over Centralized Administration

### PR DESCRIPTION
**Pull request by yrudman**
ISSUE:
 Attempt to reconfigure vm on global region raises ```Unsupported request class VmCloudReconfigureRequest``` error

AFTER:
after

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1710808

@miq-bot add-label bug, changelog/yes

### CODE REVIEW

**Comment by yrudman** [comment]
travis failure is not related to changes in this PR and should be fixed in https://github.com/ManageIQ/manageiq-api/pull/611

**Comment by yrudman** [comment]
@miq-bot add-label  hammer/yes

**Comment by simaishi** [comment]
Hammer backport details:

```
$ git log -1
commit 415422fa6f37544e05d0e78d4346684ffe4d42dd
Author: Gregg Tanzillo <gtanzillo@gmail.com>
Date:   Wed Jun 19 09:10:40 2019 -0400

    Merge pull request #608 from yrudman/allow-reconfigure-cloud-vm-over-central-admin
    
    Allow reconfigure vm on OSP provider over Centralized Administration
    
    (cherry picked from commit d82f179af5464086a7d38e59ccf8015581452174)
    
    Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1724715
```

**Pull request merged**
