### PR TITLE
Remove openshift deployment

### PR DESCRIPTION
**Pull request by d-m-u**
Per https://bugzilla.redhat.com/show_bug.cgi?id=1672937 we're removing deployment, yay. 

~~There's additional UI work that I'm afraid of doing because it's highly likely that I will break things.~~
~~The UI PR that added the majority of stuff we're removing is https://github.com/ManageIQ/manageiq/pull/7620.~~

Buncha related deletion PRs...

I think order of merge probably looks like this:
~~UI~~ 
~~(mostly done in https://github.com/ManageIQ/manageiq/pull/18095 and~~ 
~~https://github.com/ManageIQ/manageiq-ui-classic/pull/4770)~~

API
Automate
Content
Main

## Depends on:
UI -- it'd be nice to get a UI person to check that this removal is done

## Related: 
https://github.com/ManageIQ/manageiq/pull/18515
https://github.com/ManageIQ/manageiq-content/pull/511
https://github.com/ManageIQ/manageiq-automation_engine/pull/301

### CODE REVIEW

**Comment by d-m-u** [comment]
@miq-bot add_label technical debt

**Comment by d-m-u** [comment]
@miq-bot add_reviewer @tinaafitz 
@miq-bot assign @gmcculloug

**Comment by d-m-u** [comment]
@miq-bot unassign @gmcculloug

**Comment by d-m-u** [comment]
@miq-bot assign @gtanzillo

**Comment by d-m-u** [comment]
@miq-bot add_label hammer/no

**Comment by d-m-u** [comment]
I think spec failures are unrelated to any of this code

**Comment by d-m-u** [comment]
@miq-bot remove_label wip

**Comment by d-m-u** [comment]
@bdunne can I get you to 👀 please?

**Comment by abellotti** [comment]
LGTM!! Thanks @d-m-u for the updates here in the API. 👍

**Comment by d-m-u** [comment]
any chance this could possibly get merged today please?

**Comment by d-m-u** [comment]
thanks @gtanzillo :)

**Pull request merged**
