### PR TITLE
Fix console specs to align with changes to console logic

### PR DESCRIPTION
**Pull request by jntullo**
This will fix the related specs that are failing on both master and gaprindashvili after recent changes were made to require credentials for consoles

### CODE REVIEW

**Comment by abellotti** [comment]
LGTM!! will merge when 🍏

**Comment by simaishi** [comment]
Gaprindashvili backport details:

```
$ git log -1
commit e38b1cf89393220066dfcf6a6fa0d8857136db61
Author: Alberto Bellotti <abellotti@users.noreply.github.com>
Date:   Fri Mar 9 12:03:48 2018 -0500

    Merge pull request #344 from jntullo/fix_console_spec
    
    Fix console specs to align with changes to console logic
    (cherry picked from commit 45e1ac7a4ccd026851f1993cad8d1089e6ba7401)
```

**Comment by simaishi** [comment]
@jntullo Fine branch also has the same Travis error. Can this PR go to Fine branch as is?

**Comment by jntullo** [comment]
@simaishi I will create a separate PR for fine

**Comment by simaishi** [comment]
@jntullo Thank you!

**Comment by simaishi** [comment]
Backported to Fine via https://github.com/ManageIQ/manageiq/pull/17155

**Pull request merged**
