### PR TITLE
Added endpoints for physical storage families, resources and services

### PR DESCRIPTION
**Pull request by galoiring**
We added the relevant endpoints and controllers.
They will be needed to access capability values fields added in:
https://github.com/ManageIQ/manageiq-schema/pull/676

Screen Shot 2022-12-04 at 16 35 16

Screen Shot 2022-12-04 at 16 36 05

Screen Shot 2022-12-04 at 16 36 46

W/ @OrGur1987

### CODE REVIEW

**Comment by OrGur1987** [comment]
> @galoiring can you add spec tests for these new endpoints? The `spec/requests/physical_racks_spec.rb` looks like a good basic controller to model off of

we added the specs but didn't manage to run them locally on our machine (some problem with `api_basic_authorize()`.
also, we seem to fail in `api_config_spec.rb` on 'contains only valid MiqProductFeature identifiers'

**Comment by agrare** [comment]
Those are valid failures, product features for new api endpoints must be added to https://github.com/ManageIQ/manageiq/blob/master/db/fixtures/miq_product_features.yml

**Comment by OrGur1987** [comment]
> Those are valid failures, product features for new api endpoints must be added to https://github.com/ManageIQ/manageiq/blob/master/db/fixtures/miq_product_features.yml

https://github.com/ManageIQ/manageiq/pull/22274

**Comment by agrare** [comment]
@miq-bot cross-repo-tests https://github.com/ManageIQ/manageiq/pull/22274

**Comment by agrare** [comment]
@galoiring please review the failures in https://github.com/ManageIQ/manageiq-cross_repo-tests/actions/runs/3676827582/jobs/6217967590

The authentication ones aren't related but the rest look like they are introduced by this PR.  Please run the -api specs locally with your manageiq changes applied and the core repo linked via `spec/manageiq -> ../manageiq`

**Comment by galoiring** [comment]
@miq-bot cross-repo-tests https://github.com/ManageIQ/manageiq/pull/22274

**Comment by llivne** [comment]
@miq-bot cross-repo-tests https://github.com/ManageIQ/manageiq/pull/22274

**Comment by agrare** [comment]
Core PR with product features has been merged

**Comment by agrare** [comment]
@galoiring the spec failure looks legit please address

**Comment by galoiring** [comment]
@agrare  fixed.

**Pull request merged**
