### PR TITLE
Allow Servers to be edited and deleted

### PR DESCRIPTION
**Pull request by djberg96**
Followup to https://github.com/ManageIQ/manageiq-api/pull/691.

Completes https://bugzilla.redhat.com/show_bug.cgi?id=1753806

~~WIP for now until I can figure out why the 3 pending specs are failing.~~

### CODE REVIEW

**Comment by djberg96** [comment]
@martinpovolny, @lpichler, @abellotti I need an extra set of eyes to see why the delete operations are failing.

Also, I see we changed the identifier for the settings operations, please let me know if what I've done here conflicts with that in any way.

Lastly, please double check the list of restricted attributes and see if you think it's ok. I was eyeballing it a bit, just looking for attributes that are (presumbably) determined through diagnostics and shouldn't be set directly.

**Comment by Fryguy** [comment]
@carbonin Are there potential issues with anything exposed here?

**Comment by Fryguy** [comment]
@djberg96 Are all of these attributes editable via the UI?  Any that are not editable should probably be blocked here (I see you have some, but I'm not sure on the rest).

I'm also not sure on deletes at all.  Do we allow deletes from the UI?

**Comment by carbonin** [comment]
I don't see why we should allow editing anything other than name and zone.

I think almost everything else is set by the system or *really* shouldn't be edited (`guid`, `status`, `pid`, `version`...)

**Comment by djberg96** [comment]
As per @himdel's notes, the MiqServer model has some restrictions on whether or not a server can be deleted, so that's why they were failing. I've updated the factories so that they pass those internal checks. I've also added some specs that explicitly check to make sure a server is not deleted if it's not considered deleteable.

In addition, as per @carbonin's comments, I've switched from a blacklist to a whitelist of valid attributes. Right now it's only name and zone.

**Comment by Fryguy** [comment]
@djberg96 Did you determine if servers are deletable from the UI?  If not, then we shouldn't allow delete from the API either.

We have to be very careful with server records because they are the core of the entire worker management system.  Exposing that to end users should be more delicate than other objects.

**Comment by djberg96** [comment]
@himdel Thanks.

Though, for the specs to pass, the ability to edit and/or delete a server has to be a supported product feature, which is the spec that's failing now.

Do we want to add the ability to edit and/or delete servers? If so, I'll need to add a schema migration.

**Comment by djberg96** [comment]
@himdel Thanks.

I've updated the config/api.yml file to use `ops_settings` which is the identifier used for the server settings screen in general.

**Comment by djberg96** [comment]
@miq-bot add_reviewer @lpichler

**Comment by djberg96** [comment]
Note that I've updated this PR so that it uses a whitelist, so only two attributes are editable now. I've also added some specs that verify that you can't delete a server that isn't deletable.

**Comment by martinpovolny** [comment]
Code looks good. Tests look great. It works.

The moving of the similar code dealing with editability of attributes is to be done in a separate PR.

@lpichler : merge?

**Comment by simaishi** [comment]
@djberg96 can this be `ivanchuk/yes`?

**Comment by djberg96** [comment]
@simaishi I don't see why not. @martinpovolny Any objections?

**Comment by simaishi** [comment]
^ ping

**Comment by djberg96** [comment]
@simaishi I say yes. :)

**Comment by simaishi** [comment]
Ivanchuk backport details:

```
$ git log -1
commit 37338994e6881a205c8e5c23cbdeae9147ac3961
Author: Libor Pichler <lpichler@redhat.com>
Date:   Wed Nov 6 13:56:43 2019 +0100

    Merge pull request #695 from djberg96/server_post_actions2

    Allow Servers to be edited and deleted

    (cherry picked from commit 57b7037eff3c3acf993613f69b80d9a03415922a)

    Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1805844
```

**Pull request merged**
