### PR TITLE
[Changelog] Update for Hammer-3

### PR DESCRIPTION
**Pull request by JPrause**
[skip ci]

### CODE REVIEW

**Comment by JPrause** [comment]
@miq-bot add_label documentation

**Comment by JPrause** [comment]
@miq-bot add_label hammer/yes

**Comment by JPrause** [comment]
@abellotti @carbonin as time permits, can one of you review/merge.

**Comment by simaishi** [comment]
Hammer backport details:

```
$ git log -1
commit 570ac585f235b52adc3a6aacf1eb91ee0fd03acc
Author: Satoe Imaishi <simaishi@redhat.com>
Date:   Tue Mar 5 10:24:20 2019 -0500

    Merge pull request #559 from JPrause/hammer3_cl
    
    [Changelog] Update for Hammer-3
    
    (cherry picked from commit 0b0de773d58fd2965dd6ca03ea3e590925de2ebc)
```

**Pull request merged**
