### PR TITLE
Convert AuthKey operations to SupportsFeatureMixin

### PR DESCRIPTION
**Pull request by chessbyte**
Goes with https://github.com/ManageIQ/manageiq/pull/21457

### CODE REVIEW

**Comment by chessbyte** [comment]
the API spec is failing [here](https://app.travis-ci.com/github/ManageIQ/manageiq-cross_repo-tests/jobs/540091764).  I need some help understanding why this worked before and is now broken.  @kbrock maybe you can take a look.

**Comment by chessbyte** [comment]
Spec is failing because it is validating against an instance of `ManageIQ::Providers::CloudManager::AuthKeyPair` which, by definition, does not support delete whereas an instance of `ManageIQ::Providers::Amazon::CloudManager::AuthKeyPair` does.  @agrare ideas?

**Comment by kbrock** [comment]
elsewhere I was using something like:

```ruby
      expect(akp.class).to receive(:supports?).with(:delete).and_return(true)
      # or
      expect_any_instance_of(akp.resource.class).to receive(:supports?).with(:key_pair_delete).and_return(true)
```

Currently you are using the second one / the ems version but as you know, I'm trying to nudge us towards the first

**Comment by kbrock** [comment]
@chessbyte check out https://github.com/ManageIQ/manageiq-api/pull/1079

In helpers I added methods to help us with models support.
If you feel this needs to be used in all repos, I can move into manageiq core.

```ruby
      stub_action_supports(akp.class, :delete)
      # or
      stub_action_supports(akp.resource, :key_pair_delete)
```

**Comment by chessbyte** [comment]
@kbrock thanks for the suggestions.  Ended up using
```ruby
expect_any_instance_of(akp.class).to receive(:supports?).with(:delete).and_return(true)
```

**Review by agrare — APPROVED** [review]

**Pull request merged**
