### PR TITLE
Adding support for check_compliance action on providers

### PR DESCRIPTION
**Pull request by lfu**
- Adding support for check_compliance action on provider resources.
  - /api/providers/:id  - action "check_compliance"
  - /api/providers      - action "check_compliance" for bulk requests
- Added Specs

- [x] Depends on https://github.com/ManageIQ/manageiq/pull/20080.

https://github.com/ManageIQ/manageiq-api/issues/790

@miq-bot assign @abellotti

### CODE REVIEW

**Comment by abellotti** [comment]
for the travis failure, the renamed shared example maybe ?

**Comment by Fryguy** [comment]
Merged the dependent PR

**Comment by abellotti** [comment]
This is great @lfu  👍  gotta love the short and sweet pattern with the shared rspec. Thanks for the enhancement.

Will merge when ✅

**Comment by simaishi** [comment]
Jansa backport details:

```
$ git log -1
commit 24513b3ad438cc49915b7bbcc8c229a4da06c565
Author: Alberto Bellotti <abellotti@users.noreply.github.com>
Date:   Fri Apr 17 17:39:32 2020 -0400

    Merge pull request #803 from lfu/check_compliance_providers

    Adding support for check_compliance action on providers

    (cherry picked from commit fdc94421077ecedfc509c413b17a566d07dbebd0)
```

**Pull request merged**
