### PR TITLE
[Changelog] Add Hammer-B1 and Sprint 97

### PR DESCRIPTION
**Pull request by JPrause**
[skip ci]

### CODE REVIEW

**Comment by JPrause** [comment]
@miq-bot add_label documentation

**Comment by JPrause** [comment]
@miq-bot add_label hammer/no

**Comment by JPrause** [comment]
@abellotti can you review.

**Comment by JPrause** [comment]
@carbonin can you merge. Alberto approved.

**Comment by carbonin** [comment]
No I can't, but @abellotti can.

**Pull request merged**
