### PR TITLE
add tags as lan subcollection

### PR DESCRIPTION
**Pull request by d-m-u**
~~it's wip because the identifiers are wrong but i'm not even sure we have identifiers for lans?~~ 
it needs a review or nineteen

Addresses https://github.com/ManageIQ/manageiq-api/issues/801

### CODE REVIEW

**Comment by d-m-u** [comment]
@miq-bot add_label enhancement

**Comment by abellotti** [comment]
could be related to the identifiers used to access lans for, i.e.

```
        - ems_cluster_show_list
        - host_show_list
        - instance_show_list
        - vm_show_list
```

maybe we need:

```
        - ems_network_tag
        - infra_networking_tag
```

And possibly others in db/fixtures/miq_product_features.yml

 @h-kataria would knows more.

**Comment by h-kataria** [comment]
> could be related to the identifiers used to access lans for, i.e.
> 
> ```
>         - ems_cluster_show_list
>         - host_show_list
>         - instance_show_list
>         - vm_show_list
> ```
> 
> maybe we need:
> 
> ```
>         - ems_network_tag
>         - infra_networking_tag
> ```
> 
> And possibly others in db/fixtures/miq_product_features.yml
> 
> @h-kataria would knows more.

@d-m-u , @abellotti is correct looks like you are missing
```
infra_networking_tag
ems_network_tag
```
You might also need these
```
network_port_tag
network_router_tag
```

**Comment by d-m-u** [comment]
anyone want to please review this?

**Pull request merged**
