### PR TITLE
Allow bulk assignment and unassignment of tags for users

### LINKED ISSUE #459: Enable bulk assignment of tags for users
I am now working on tag assignment React component for users in MIQ. You can edit multiple tags for multiple users at once. If i want to use API i have to create one request per user to edit their tags. That is not very pretty sollution.

Is it possible to add bulk assignment of tags to users (like for vms of services)?

### PR DESCRIPTION
**Pull request by skateman**
Resolves #459

http://manageiq.org/docs/reference/latest/api/reference/tagging#bulk-assigning-tags

cc @Hyperkid123

### CODE REVIEW

**Comment by abellotti** [comment]
Thanks @skateman for the API Enhancement.  This LGTM!! 👍

**Comment by abellotti** [comment]
Hey @skateman the specs test POST /api/users/:id/tags  (assign and unassign), I think you need to also add tests  for POST /api/users  (assign_tags and unassign_tags)

**Comment by skateman** [comment]
@abellotti sure, but I haven't seen any other similar test and the way I'm trying is failing:
```ruby
      api_basic_authorize collection_action_identifier(:users, :assign_tags)

      post(api_users_url(:params => gen_request(:assign_tags, [
        {:href => api_user_url(nil, user1), :tags => [tag1, tag2]},
        {:href => api_user_url(nil, user2), :tags => [tag1, tag2]}
      ])))
```
I am getting a *Use of Action create is forbidden*, while the action is `asssign_tags`. If I try to change the authorization to `collection_action_identifier(:users, :create)`, I'm getting a *bad request* error.

**Comment by abellotti** [comment]
take a look at the assign_tags/unassign_tags tests for vms and services in the tag_collections_spec.rb file. Hopefully the answer is there.

**Pull request merged**
