### PR TITLE
[Changelog] Update for Ivanchuk Beta1 release

### PR DESCRIPTION
**Pull request by JPrause**
[skip ci]

### CODE REVIEW

**Comment by JPrause** [comment]
@miq-bot add_label documentation

**Comment by JPrause** [comment]
@miq-bot add_label ivanchuk/yes

**Comment by simaishi** [comment]
@JPrause looks like Sprint 116 changelog didn't get added before creating this PR...

**Comment by simaishi** [comment]
Ivanchuk backport details:

```
$ git log -1
commit 61e0b85c6f44aa77834862249ee2d687e3a8380c
Author: Alberto Bellotti <abellotti@users.noreply.github.com>
Date:   Fri Jul 26 13:34:19 2019 -0400

    Merge pull request #635 from JPrause/ivanb1_cl
    
    [Changelog] Update for Ivanchuk Beta1 release
    
    (cherry picked from commit 569e9c3dbc1842d071b3f720721b0cd6c866c3c6)
```

**Pull request merged**
