### PR TITLE
Include product features list in the identity section of /api

### PR DESCRIPTION
**Pull request by skateman**
As we were discussing about it [on gitter](https://gitter.im/ManageIQ/api?at=5bbb5da85331811c2e6b5336) the UI should be informed through the API about what the user is allowed to do. SUI has a `sui_product_features` for this, so I analogously created `product_features` at the same location.

```js
// $ GET http://admin:smartvm@localhost:3000/api | jq -r .identity.miq_groups

[
  {
    "href": "http://localhost:3000/api/groups/2",
    "id": "2",
    "description": "EvmGroup-super_administrator",
    "group_type": "system",
    "sequence": 1,
    "created_on": "2017-10-06T16:35:38Z",
    "updated_on": "2017-10-06T16:35:38Z",
    "settings": null,
    "tenant_id": "1",
    "sui_product_features": [
      "sui_app_launcher",
      "sui_vm_details_view",
      // ...
    ],
    "product_features": [
      "everything"
    ]
  }
]
```

This should fix the problems @Hyperkid123 has with [custom button events](https://bugzilla.redhat.com/show_bug.cgi?id=1634053) in his new [RBAC UI PR](https://github.com/ManageIQ/manageiq-ui-classic/pull/4562).

### CODE REVIEW

**Comment by himdel** [comment]
LGTM, works for me :)

**Comment by Fryguy** [comment]
LGTM

**Comment by Fryguy** [comment]
@bdunne Please review and if you are good, please merge.

**Comment by martinpovolny** [comment]
ping @bdunne ?

**Pull request merged**
