### PR TITLE
Fix CloudNetworks spec with empty including()

### PR DESCRIPTION
**Pull request by agrare**
This spec was unchanged since being introduced in fa4e0a618f4 but a bump to rspec-expectations `3.13.2` raised the issue that it wasn't actually testing anything.

### CODE REVIEW

**Comment by jrafanie** [comment]
@agrare should the tests be passing?  😕

**Comment by agrare** [comment]
> should the tests be passing? 😕

No, this only fixes the cloud_networks spec not the resource_pool identifier issue.

**Review by Fryguy — APPROVED** [review]

**Comment by jrafanie** [comment]
Merging.  We have other failures to be fixed outside of this PR.

**Comment by jrafanie** [comment]
Marked for radjabov/yes? since we can pull in rspec-expectations 3.13.2 on that branch too.

**Comment by Fryguy** [comment]
Backported to `radjabov` in commit 3803fa5647a1401f42bf3e49622f1067a52ee1ee.

```text
commit 3803fa5647a1401f42bf3e49622f1067a52ee1ee
Author: Joe Rafaniello <jrafanie@users.noreply.github.com>
Date:   Fri Aug 30 14:21:35 2024 -0400

    Merge pull request #1267 from agrare/fix_cloud_networks_a_collection_including
    
    Fix CloudNetworks spec with empty including()
    
    (cherry picked from commit 4e4e1a07c1f14575a11ad8eb09265331f96adba4)
```

**Comment by Fryguy** [comment]
Backported to `quinteros` in commit c195eab46bc1e31301d49401ab8d29686fc4ef2c.

```text
commit c195eab46bc1e31301d49401ab8d29686fc4ef2c
Author: Joe Rafaniello <jrafanie@users.noreply.github.com>
Date:   Fri Aug 30 14:21:35 2024 -0400

    Merge pull request #1267 from agrare/fix_cloud_networks_a_collection_including
    
    Fix CloudNetworks spec with empty including()
    
    (cherry picked from commit 4e4e1a07c1f14575a11ad8eb09265331f96adba4)
```

**Pull request merged**
