### PR TITLE
[Changelog] Update for Hammer-4

### PR DESCRIPTION
**Pull request by JPrause**
[skip ci]

### CODE REVIEW

**Comment by JPrause** [comment]
@miq-bot add_label documentation

**Comment by JPrause** [comment]
@miq-bot add_label hammer/yes

**Comment by JPrause** [comment]
@abellotti as time permits, can you review merge. We need this for today's build.

**Comment by simaishi** [comment]
Hammer backport details:

```
$ git log -1
commit decea6c15936e01042feedeea30bb211fc6f8c71
Author: Alberto Bellotti <abellotti@users.noreply.github.com>
Date:   Wed Mar 27 09:12:01 2019 -0400

    Merge pull request #569 from JPrause/hammer4_cl
    
    [Changelog] Update for Hammer-4
    
    (cherry picked from commit 55621be8daa656acbaedfd58bc9a52519dc7b75f)
```

**Pull request merged**
