### PR TITLE
Allow generic object definition picture to be removed via edit

### PR DESCRIPTION
**Pull request by jntullo**
#### Usage
```
{
  "action"    : "edit",
  "resources" : [
  { "id" : ":id", "resource" : { "name" : "updated 1", "picture" : {} } }
  ]
}
```

@miq-bot assign @abellotti 
@miq-bot add_label enhancement
cc: @AparnaKarve

### CODE REVIEW

**Comment by abellotti** [comment]
I think this is fine, essentially un-assigning the picture from the generic object definition.

If someone wants to also delete the picture from the vmdb, would that be the separate call to the picture resource ?  I'm curious as to what happens if someone deletes a picture then we fetch a generic object definition asking for the image, is that nil or bogus ?

**Comment by AparnaKarve** [comment]
> If someone wants to also delete the picture from the vmdb, would that be the separate call to the picture resource

Good question.
I think it needs to be a separate call, since it is a separate concern.
But then OTOH, the Generic Object Definition `Create` API was responsible for creating the picture, so why not let the API un-assign the picture record and also delete it? 
( I don't know :) )

@abellotti I created this PR - https://github.com/ManageIQ/manageiq/pull/16163 that will enable us to get the `picture_url_path` for an existing Generic Object Definition record.

What I noticed was, it is important to set `:allow_nil => true`
Otherwise we end up getting this -
```
{
  "error": {
    "kind": "internal_server_error",
    "message": "GenericObjectDefinition#picture_url_path delegated to picture.url_path, but picture is nil: #<GenericObjectDefinition id: 10000000000080, name: \"a11\", description: \"a\", properties: {:attributes=>{}, :associations=>{}, :methods=>[]}, created_at: \"2017-10-09 22:31:05\", updated_at: \"2017-10-09 22:31:05\">",
    "klass": "Module::DelegationError"
  }
}
```

**Comment by jntullo** [comment]
@abellotti @AparnaKarve meant to post this earlier, sorry

but it actually removes and deletes the resource all in one call, since on the model it is set as `:dependent => :destroy` here https://github.com/ManageIQ/manageiq/blob/master/app/models/generic_object_definition.rb#L20

**Comment by AparnaKarve** [comment]
@jntullo That's great. Problem solved :)
Thanks for that link.

**Comment by abellotti** [comment]
so the remaining question is the travis failure.

**Comment by jntullo** [comment]
@abellotti working on it 👍

**Comment by jntullo** [comment]
Fix: https://github.com/ManageIQ/manageiq/pull/16164

**Comment by abellotti** [comment]
LGTM!! Thanks @jntullo for the API enhancement.

**Pull request merged**
