### PR TITLE
Bump master travis.yml to ruby 2.3.8.

### PR DESCRIPTION
**Pull request by jrafanie**
Bump master travis.yml to ruby 2.3.8.

### CODE REVIEW

**Comment by jrafanie** [comment]
@miq-bot add_label gaprindashvili/yes
@miq-bot add_label hammer/yes

**Comment by jrafanie** [comment]
@NickLaMuro looks like we starting failing at your commit on master: https://github.com/ManageIQ/manageiq-api/commits, https://travis-ci.org/ManageIQ/manageiq-api/builds/466788062?utm_source=github_status&utm_medium=notification, can you take a look?  Is it related to your PR?

**Comment by NickLaMuro** [comment]
@jrafanie sure, looking.  Will be a bit since I am just finishing up looking into something else.

**Comment by NickLaMuro** [comment]
@jrafanie I will look into this a bit more, but I don't think this was my fault, just bad timing.  Based on the errors, it seems like this was merged:

https://github.com/ManageIQ/manageiq/pull/18277

And caused issues with the validations in these specs.  Will look into seeing what needs to change for these to work again.

/cc @djberg96

**Comment by NickLaMuro** [comment]
Of note:  Seems like this commit is a bit of a problem:

https://github.com/ManageIQ/manageiq/commit/e17c00a43208d9d4e5649d006c55543afec0dd5e

Seems like what the API has expected was a pretty loose expectation for `ResourceType`, but the validation only accepts those two specific types:

https://github.com/ManageIQ/manageiq-api/blob/01ee85a6/spec/requests/conversion_hosts_spec.rb#L56
https://github.com/ManageIQ/manageiq-api/blob/01ee85a6/spec/requests/conversion_hosts_spec.rb#L65

Not sure we want to be so restrictive, but as this is a new feature in the API, maybe it doesn't matter.  Opening up a new PR shortly to fix things.

**Comment by NickLaMuro** [comment]
PR to fix specs:  https://github.com/ManageIQ/manageiq-api/pull/524

**Comment by simaishi** [comment]
Hammer backport details:

```
$ git log -1
commit 82f81ba3c750dc61522a6ff7b288e3b5185903ff
Author: Jason Frey <fryguy9@gmail.com>
Date:   Fri Dec 14 14:51:00 2018 -0500

    Merge pull request #523 from jrafanie/master_bump_travis_to_238
    
    Bump master travis.yml to ruby 2.3.8.
    
    (cherry picked from commit 30df196937eda7243d3ff0f172f9f4c8df9d8bd9)
```

**Comment by simaishi** [comment]
Gaprindashvili backport details:

```
$ git log -1
commit df1bacb5b05c5cd31f847698112c18ceea4d61db
Author: Jason Frey <fryguy9@gmail.com>
Date:   Fri Dec 14 14:51:00 2018 -0500

    Merge pull request #523 from jrafanie/master_bump_travis_to_238
    
    Bump master travis.yml to ruby 2.3.8.
    
    (cherry picked from commit 30df196937eda7243d3ff0f172f9f4c8df9d8bd9)
```

**Pull request merged**
