### PR TITLE
Use the new universal methods for suspending/resuming a provider

### PR DESCRIPTION
**Pull request by skateman**
Parent issue: https://github.com/ManageIQ/manageiq/issues/17489
Depends on: https://github.com/ManageIQ/manageiq/pull/17452

cc @slemrmartin 

https://bugzilla.redhat.com/show_bug.cgi?id=1455145

### CODE REVIEW

**Comment by skateman** [comment]
@slemrmartin are these methods still safe to use?

**Comment by slemrmartin** [comment]
@skateman yes, `pause!` and `resume!` are still entry points for this PR

**Comment by jvlcek** [comment]
@skateman Since the goal is to try to have every PR include a related spec test perhaps you could update https://github.com/ManageIQ/manageiq-api/blob/master/spec/requests/providers_spec.rb to ensure the new methods are received.

It shouldn't be too hard to add.

Besides that 👍 LGTM

**Comment by skateman** [comment]
@jvlcek there are already tests for this feature, I'm just changing the method to be called on the model. So I don't really understand what else should I test here, can you please clarify?

**Comment by jvlcek** [comment]
@skateman Understood and agreed. I was just thinking that maybe an
`expect(X).to receive(:pause!)` could be added to the `pause a provider` test but on second thought it's not overly valuable.

I'm OK with this PR as it is.

JoeV

**Pull request merged**
