### PR TITLE
Permit concurrent loads to avoid a deadlock

### PR DESCRIPTION
**Pull request by jrafanie**
https://bugzilla.redhat.com/show_bug.cgi?id=1596703
https://bugzilla.redhat.com/show_bug.cgi?id=1595832

If two web service worker threads both receive a request and have not yet
initialized time_attributes, it's possible for the threads to deadlock as
described below.

**Thread 1**:
constantizes CloudObjectStoreContainer, which tries to include_concern
"Operations" (note: the constant is not yet loaded)... and waits for a
lock held by thread 2

**Thread 2**:
constantizes CloudObjectStoreContainer, acquires a lock and sits and
waits on something else

It's unclear why thread 2 is holding a lock and will not relinquish it.

For now, we can protect this constantize by wrapping
each constantize in this method in a permit_concurrent_loads block.

Note, several other classes successfully load concurrently, but
CloudObjectStoreContainer consistently hits this.  It is the first class
that tries to constantize that also does include_concern so it's
possible this combination will be responsible for the eventual fix.

To test this:

1) Add rails lock debugging middleware to config/application.rb:
   `config.middleware.insert_before Rack::Sendfile, ActionDispatch::DebugLocks`

2) Copy this script to /var/www/miq/vmdb:

```ruby
Thread.new do
  `curl -k -L https://admin:smartvm@localhost/api/notifications?expand=resources&attributes=details&sort_by=id&sort_order=desc&limit=100`
end

Thread.new do
  `curl -k -L https://admin:smartvm@localhost/api/notifications?expand=resources&attributes=details&sort_by=id&sort_order=desc&limit=100`
end
```

3) `systemctl start evmserverd` (or restart if you added the middleware in
step 1)

4) run the script in step 2.  `ruby path/to/file`.

5) Hit the locks endpoint added in step 1): `curl -L http://admin:smartvm@localhost:4000/rails/locks`

6) If the locks endpoint shows locks, run it again as it could be a
temporary lock.  With the fixed code, the curl command should have no
output.  With the broken code, it outputs the threads, their backtraces
and who's blocking whom.

### CODE REVIEW

**Comment by jrafanie** [comment]
cc @gtanzillo @Fryguy @carbonin

**Comment by jrafanie** [comment]
@miq-bot add_label gaprindashvili/yes

**Comment by jrafanie** [comment]
@miq-bot add_label bug

**Comment by jrafanie** [comment]
🎩 tip to @carbonin for his super simple reproducer script in step 2.  Many a keyboard key were slammed in order to get to that simple script.

**Comment by simaishi** [comment]
Gaprindashvili backport details:

```
$ git log -1
commit 34466f19a2db32e3152c9cb345466c723e593308
Author: Jason Frey <fryguy9@gmail.com>
Date:   Tue Jul 10 16:51:01 2018 -0400

    Merge pull request #416 from jrafanie/interlock_permit_concurrent_loads_when_constantizing
    
    Permit concurrent loads to avoid a deadlock
    (cherry picked from commit 325e0bf160dbe627db2fa971bdc111a4db1f27f4)
    
    Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1600191
    Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1600192

```

**Pull request merged**
