### PR TITLE
metric rollups api

### PR DESCRIPTION
**Pull request by jntullo**
Dependent on: https://github.com/ManageIQ/manageiq/pull/15549

### Metric rollups API requires the following parameters:
* resource_type
* capture_interval
* start_date 

### Optional parameters:
* resource_ids
  * If no resource_ids are specified, it will return all of the metric rollups for that collection
* end_date
  * if no end_date is specified, it will use the current date 

### Paging 
* Paging will be automatically applied to these metric rollup requests 
* the limit may be overriden, but is set by default in the api settings

### Examples
 `GET /api/metric_rollups?resource_type=VmOrTemplate,resource_ids=[1,2,3],capture_interval=hourly,start_date='2017-08-22 08:57:52 -0400'`

 `GET /api/metric_rollups?resource_type=VmOrTemplate,resource_ids=[1,2,3],capture_interval=hourly,start_date=2017-08-01,end_date=2017-08-22`

Dates are in the format:
`YYYY-MM-DD` or `YYYY-MM-DDTHH:MM:SSZ`

@miq_bot add_label wip, api
@miq-bot assign @abellotti

### CODE REVIEW

**Comment by jntullo** [comment]
@miq-bot remove_label wip

**Comment by abellotti** [comment]
could you update the PR description to mention dates in the API supported form  (YYYY-MM-DD & YYYY-MM-DDTHH:MM:SSZ)

**Comment by abellotti** [comment]
LGTM!! Thanks @jntullo, minor changes needed.

**Comment by abellotti** [comment]
Thanks @jntullo for the update.  LGTM!!

Please have a follow-up PR for the codeclimate issue, thanks.

**Comment by abellotti** [comment]
Hi @jntullo we will need all these parameters supported by the cli, exe/rest_api.rb.  Thanks.

**Pull request merged**
