### PR TITLE
Remove blueprint

### PR DESCRIPTION
**Pull request by bzwei**
Blueprint feature has been removed. Dependencies on API need to be removed before I can remove blueprint from the model.

### CODE REVIEW

**Comment by bzwei** [comment]
@miq-bot add_label technical_debt
@miq-bot assign @abellotti 
cc @gmcculloug

**Comment by bzwei** [comment]
@miq-bot add_label technical debt

**Comment by abellotti** [comment]
_Note_  manageiq.org documentation should be updated to remove blueprint from the 3.0.0 api docs.

**Comment by abellotti** [comment]
Thanks @bzwei for this PR.  Looks like it's not used at all from SUI.  We're good.

I'll just mention it in the manageiq.org API doc for 3.0.0.

**Pull request merged**
