### PR TITLE
Add an ansible endpoint to allow users to execute playbooks

### PR DESCRIPTION
**Pull request by felipedf**
This PR provides an endpoint to execute ansible playbooks

Depends on: ~https://github.com/ManageIQ/manageiq/pull/18059~
                    ~https://github.com/ManageIQ/manageiq-providers-lenovo/pull/246~

### CODE REVIEW

**Comment by djberg96** [comment]
@felipedf Can you please add specs and cleanup the codeclimate issues (if possible)?

**Comment by djberg96** [comment]
@felipedf Looks like the dependent PR's were merged. Did you no longer want this?

**Comment by d-m-u** [comment]
Anyone know why this got closed?

**Comment by felipedf** [comment]
hey @djberg96 and @d-m-u, I stopped working on this, so I closed it

**Pull request closed without merging**
