### PR TITLE
Allow patch/put/delete methods on the CloudNetwork resource

### PR DESCRIPTION
**Pull request by skateman**
REST should be REST :wink:

FYI @gubbe505 
@miq-bot add_label enhancement
@miq-bot assign @lpichler

### CODE REVIEW

**Comment by Fryguy** [comment]
Why is this WIP?

**Comment by skateman** [comment]
> Why is this WIP?

because I forgot :see_no_evil:

**Review by lpichler — APPROVED** [review]

**Comment by abellotti** [comment]
Missing specs

**Comment by abellotti** [comment]
Nothing automatic spec wise for routes. Put/Patch logic was tested via Post edit action, true, but not routes. However delete logic would be 100% new.  

Also, this is leveraging he generic delete, so sync not async delete.  Is this ok for cloud network resources ?

**Comment by skateman** [comment]
How can I force this to leverage the non-generic delete? There's a `delete_resource` method defined in the controller...

**Comment by abellotti** [comment]
ahh, nm!!  If delete_resource code is already there (didn't see it in this PR), then that's what gets called from the generic handler.

**Pull request merged**
