### PR TITLE
Add update action for templates

### PR DESCRIPTION
**Pull request by andyvesel**
Added `update` action for images
https://bugzilla.redhat.com/show_bug.cgi?id=1487114

### CODE REVIEW

**Comment by andyvesel** [comment]
@abellotti @jntullo we need here tests with POST and PUT, and also a bulk test, correct?

**Comment by andyvesel** [comment]
@abellotti could you review?

**Comment by abellotti** [comment]
Same here @andyvesel, merge conflict.

**Comment by andyvesel** [comment]
@miq-bot remove_label unmergeable

**Comment by andyvesel** [comment]
@abellotti could you review?

**Comment by abellotti** [comment]
LGTM!! Thanks @andyvesel for the API Enhancement 👍

**Pull request merged**
